"""create table birds

Revision ID: 0251d7ed79b2
Revises: 
Create Date: 2024-02-18 13:22:31.131602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0251d7ed79b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birds')
    # ### end Alembic commands ###
